<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('user_productivities', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->onDelete('cascade');
            $table->date('date');
            
            // Core Fact Sheet: Totals, averages, and context switching counts
            $table->json('stats_json')->nullable();
            
            // Task Deep Dive: Array of tasks containing their specific URL heartbeats and Spatie events
            $table->json('tasks_json')->nullable();
            
            // Timeline Barcode: 144 or 1440 points representing activity states for the UI
            $table->json('timeline_json')->nullable();
            
            // AI Narrative: The interpretations generated by Gemini
            $table->json('ai_report_json')->nullable();
            
            // Accuracy & Data Integrity: Unidentified domains and percentage categorized
            $table->json('accuracy_json')->nullable();
            
            $table->string('status')->default('pending'); // pending, processing, completed, failed
            $table->timestamps();

            // Ensure we only have one snapshot per user per day
            $table->unique(['user_id', 'date']);
            $table->index('date');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('user_productivities');
    }
};
