<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Real email threading — the columns Gmail needs to hang a reply off the original.
 *
 * The important correction this migration encodes: `emails.message_id` does NOT hold
 * what In-Reply-To/References need. It stores the Gmail **API** message id (a hex handle
 * like `18f2a3b4c5d6e7f8`, from `$message->getId()` in EmailReceiveController), whereas
 * those headers must carry the RFC 5322 **Message-ID header** (`<CAF...@mail.gmail.com>`).
 * Putting the API id in them threads nothing — Gmail simply finds no match and starts a
 * new conversation. So the header value gets its own column.
 *
 * `message_id` is left exactly as it is: it is the de-duplication key the Gmail poller
 * relies on (`Email::where('message_id', $details['id'])->exists()`), and repurposing it
 * would break inbound de-duplication.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('emails', function (Blueprint $table) {
            // The RFC 5322 Message-ID header, angle brackets included. Captured from
            // inbound mail, and generated by us for outbound so replies to our own
            // messages can be threaded too.
            $table->string('rfc_message_id', 512)->nullable()->after('message_id');

            // Gmail's own conversation id. Not used for header threading (the headers are
            // what actually thread), but it lets a thread be opened in Gmail directly and
            // is useful for reconciling our conversations against theirs.
            $table->string('gmail_thread_id', 128)->nullable()->after('rfc_message_id');

            // Which message this one answers. Null on everything that exists today, which
            // is what makes the send-path changes inert for every legacy flow — the quote
            // and the threading headers are only added when this is set.
            $table->unsignedBigInteger('in_reply_to_email_id')->nullable()->after('gmail_thread_id');

            $table->index('rfc_message_id', 'emails_rfc_message_id_idx');
            $table->index('in_reply_to_email_id', 'emails_in_reply_to_idx');

            $table->foreign('in_reply_to_email_id')
                ->references('id')
                ->on('emails')
                ->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('emails', function (Blueprint $table) {
            $table->dropForeign(['in_reply_to_email_id']);
            $table->dropIndex('emails_rfc_message_id_idx');
            $table->dropIndex('emails_in_reply_to_idx');
            $table->dropColumn(['rfc_message_id', 'gmail_thread_id', 'in_reply_to_email_id']);
        });
    }
};
