<?php

namespace App\Services\Inbox;

use App\Enums\EmailType;
use App\Models\Email;
use Illuminate\Support\Str;

/**
 * Makes a reply look like a reply — to Gmail, and to the person receiving it.
 *
 * Two separate jobs, done at SEND time rather than at compose time:
 *
 * 1. **Threading headers.** Gmail groups messages by the RFC 5322 `In-Reply-To` and
 *    `References` headers. Both must carry the parent's **Message-ID header**
 *    (`<CAF…@mail.gmail.com>`) — NOT `emails.message_id`, which holds Gmail's API message
 *    id and matches nothing. That is why `rfc_message_id` exists as its own column.
 *
 * 2. **The quoted thread.** The previous messages are appended to the outgoing HTML here,
 *    and are deliberately NOT stored in `emails.body`.
 *
 * Why the quote is not stored, which is the point of this class:
 *  - The AI checker reads `emails.body`. A stored quote would mean re-sending the entire
 *    conversation to the model on every reply, so the token cost of a thread grows
 *    quadratically with its length while adding nothing — the checker is judging the new
 *    text, not the history.
 *  - It keeps the row a record of what someone actually wrote, so the thread view is not
 *    every message repeated inside every later message.
 *  - The client still receives the full quoted chain, because it is built here on the way
 *    out.
 *
 * The trade-off, stated plainly: what we store is no longer byte-identical to what was
 * sent. The reply as delivered can always be reconstructed from the row plus its
 * ancestors, and Gmail keeps the sent copy, so nothing is lost — but a diff of "what we
 * stored" against "what they got" will show the quote.
 */
class ReplyThreading
{
    /** How far back to quote. Beyond this the chain adds bulk, not context. */
    private const MAX_QUOTED = 6;

    /**
     * `In-Reply-To` / `References` for a reply, or an empty array when this email is not
     * one (or the parent predates rfc_message_id being captured).
     *
     * `References` carries the whole ancestry, oldest first, per RFC 5322 §3.6.4 — clients
     * use it to rebuild a thread when an intermediate message is missing. `In-Reply-To`
     * carries only the immediate parent.
     *
     * @return array<string,string>
     */
    public function headersFor(Email $email): array
    {
        $parent = $this->parent($email);

        if (! $parent || ! $parent->rfc_message_id) {
            return [];
        }

        $references = $this->ancestry($parent)
            ->pluck('rfc_message_id')
            ->filter()
            ->unique()
            ->values();

        $headers = ['In-Reply-To' => $parent->rfc_message_id];

        if ($references->isNotEmpty()) {
            $headers['References'] = $references->implode(' ');
        }

        return $headers;
    }

    /**
     * A Message-ID header for an outgoing email, so later replies can thread onto it.
     *
     * Generated by us rather than read back from Gmail: the send API returns its own
     * message id, not the header it stamped, and fetching the sent message afterwards to
     * read the header is a second round trip that can fail independently of the send.
     * Setting the header ourselves means the value we store is definitively the value that
     * went out.
     *
     * The domain is taken from the sending address so the id is globally unique in the
     * way the RFC intends.
     */
    public function newMessageId(Email $email, ?string $fromAddress = null): string
    {
        $domain = 'ozeeweb.com.au';

        if ($fromAddress && str_contains($fromAddress, '@')) {
            $domain = Str::after($fromAddress, '@');
        }

        return '<'.Str::uuid()->toString().'.'.$email->id.'@'.$domain.'>';
    }

    /**
     * The outgoing HTML: the reply, then the quoted chain beneath it.
     *
     * Private messages are never quoted — a manager marked them internal, and quoting one
     * into an outbound email would send it to the client, which is the exact thing the
     * flag exists to prevent. Screened inbound mail is quoted, because it came FROM the
     * person being replied to; withholding it is about who on our side may read it, not
     * about what they already know they sent us.
     */
    public function withQuotedThread(Email $email, string $renderedBody): string
    {
        $parent = $this->parent($email);

        if (! $parent) {
            return $renderedBody;
        }

        $quoted = $this->ancestry($parent)
            ->reject(fn (Email $e) => (bool) $e->is_private)
            ->reverse()          // newest first, the way mail clients show a quote
            ->take(self::MAX_QUOTED)
            ->map(fn (Email $e) => $this->quoteBlock($e))
            ->implode('');

        if ($quoted === '') {
            return $renderedBody;
        }

        // gmail_quote is the class Gmail itself uses; clients that collapse quoted history
        // recognise it, so the reply reads as a reply rather than a wall of text.
        return $renderedBody
            .'<div class="gmail_quote" style="margin-top:16px;padding-top:12px;'
            .'border-top:1px solid #e6e9ef">'
            .$quoted
            .'</div>';
    }

    /** True when this email is a reply we should thread and quote. */
    public function isReply(Email $email): bool
    {
        return $email->in_reply_to_email_id !== null;
    }

    // ---------------------------------------------------------------- internals

    private function parent(Email $email): ?Email
    {
        if (! $email->in_reply_to_email_id) {
            return null;
        }

        return Email::find($email->in_reply_to_email_id);
    }

    /**
     * The parent and everything before it on the conversation, oldest first.
     *
     * Walked by conversation and timestamp rather than by in_reply_to_email_id, because
     * only replies composed in the new inbox have that link — every email that predates
     * it would otherwise produce a one-message chain.
     *
     * @return \Illuminate\Support\Collection<int,Email>
     */
    private function ancestry(Email $parent): \Illuminate\Support\Collection
    {
        $cutoff = $parent->sent_at ?? $parent->created_at;

        return Email::query()
            ->where('conversation_id', $parent->conversation_id)
            ->where(function ($q) use ($cutoff) {
                $q->whereRaw('COALESCE(sent_at, created_at) <= ?', [$cutoff]);
            })
            ->orderByRaw('COALESCE(sent_at, created_at) ASC')
            ->limit(self::MAX_QUOTED * 2)
            ->get();
    }

    /** One quoted message, in the shape mail clients expect. */
    private function quoteBlock(Email $email): string
    {
        $who = e($this->senderLabel($email));
        $when = ($email->sent_at ?? $email->created_at)?->format('D, j M Y \a\t g:i a') ?? '';
        $body = $this->sanitiseForQuote($email->body);

        return '<div style="margin:0 0 12px">'
            .'<div style="color:#676879;font:12px/18px Arial,sans-serif;margin-bottom:4px">'
            .'On '.e($when).', '.$who.' wrote:'
            .'</div>'
            .'<blockquote style="margin:0;padding-left:12px;border-left:2px solid #d0d4e4;color:#404149">'
            .$body
            .'</blockquote>'
            .'</div>';
    }

    private function senderLabel(Email $email): string
    {
        if ($email->sender?->name) {
            return $email->sender->name;
        }

        $type = $email->type instanceof EmailType ? $email->type->value : (string) $email->type;

        return $type === EmailType::Received->value
            ? ($email->conversation?->conversable?->name ?? 'they')
            : 'OZee Web & Digital';
    }

    /**
     * Strip a quoted body back to something safe to nest.
     *
     * A stored body can be a whole HTML document (the composer's preview path stores one),
     * and nesting `<html>`/`<head>`/`<style>` inside a reply breaks the outer document and
     * lets the quote's CSS repaint it. Scripts go for the obvious reason, and an already
     * quoted chain is dropped so quoting does not compound on every reply.
     */
    private function sanitiseForQuote(?string $html): string
    {
        $body = (string) $html;

        // Keep only the inner body of a full document.
        if (preg_match('/<body[^>]*>(.*?)<\/body>/is', $body, $m)) {
            $body = $m[1];
        }

        $body = preg_replace('/<(script|style|head|title)\b[^>]*>.*?<\/\1>/is', '', $body) ?? $body;
        $body = preg_replace('/<\/?(html|head|body|meta|link|base)\b[^>]*>/i', '', $body) ?? $body;

        // Drop a quote that is already inside this message, so replies do not nest
        // exponentially down a long thread.
        $body = preg_replace('/<div class="gmail_quote".*$/is', '', $body) ?? $body;

        // Inline event handlers, which have no business in a quote.
        $body = preg_replace('/\son[a-z]+\s*=\s*("[^"]*"|\'[^\']*\'|[^\s>]+)/i', '', $body) ?? $body;

        return trim($body);
    }
}
